# Variables
# sub: ${env.SUB_DOMAIN}
stage: ${env.STAGE}
name: ${env.REPO}

serverless:
  component: '@sls-next/serverless-component@1.18.0'
  inputs:
    # memory: 2048
    # timeout: 30
    bucketRegion: us-east-1
    bucketName: ${name}-${stage}
    name:
      defaultLambda: ${name}-${stage}-default
      apiLambda: ${name}-${stage}-api
      imageLambda: ${name}-${stage}-image
    build:
      env:
        STRIPE_SK: ${env.STRIPE_SK}
        MONGODB_URI: ${env.MONGODB_URI}
        NEXTAUTH_URL: ${env.NEXTAUTH_URL}
        NEXTAUTH_SECRET: ${env.NEXTAUTH_SECRET}
        NEXT_PUBLIC_STAGE: ${stage}
        NEXT_PUBLIC_STRIPE_PK: ${env.NEXT_PUBLIC_STRIPE_PK}
    domain: ['${env.SUB_DOMAIN}', codattest.com] # sub = 'dev' || 'www' (depending on stage)
    # domain: codattest.com
    publicDirectoryCache: false
    useServerlessTraceTarget: true






# build:
#   cmd: npm # default = node_modules/.bin/next
#   args: [run, 'build'] # default = ['build']