stage: ${env.STAGE}
name: ${env.REPO}

domain:
  dev: ['dev', codattest.com]
  prod: codattest.com

url:
  dev: https://dev.codattest.com 
  prod: https://www.codattest.com

serverless:
  component: '@sls-next/serverless-component@1.18.0'
  inputs:
    useServerlessTraceTarget: true
    publicDirectoryCache: false
    bucketRegion: us-east-1
    bucketName: ${name}-${stage}
    domain: ${domain.${stage}}
    timeout: 10 # 1-900
    memory: # 128-10240
      defaultLambda: 448
      apiLambda: 640
      imageLambda: 448
    name:
      defaultLambda: ${name}-${stage}-default
      apiLambda: ${name}-${stage}-api
      imageLambda: ${name}-${stage}-image
    build:
      env:
        STRIPE_SK: ${env.STRIPE_SK}
        MONGODB_URI: ${env.MONGODB_URI}
        NEXT_PUBLIC_NEXTAUTH_URL: ${url.${stage}}
        NEXTAUTH_SECRET: ${env.NEXTAUTH_SECRET}
        NEXT_PUBLIC_STAGE: ${stage}
        NEXT_PUBLIC_STRIPE_PK: ${env.NEXT_PUBLIC_STRIPE_PK}
        JWT_SIGNING_PK: ${env.JWT_SIGNING_PK}
        RECAPTCHA_SK: ${env.RECAPTCHA_SK}
    # cloudfront:
      # distributionId: XYZEXAMPLE # if you want to use an existing cloudfront distribution, provide it here
      # aliases: ["${alias.${stage}}.codattest.com"]