sub: ${env.SUB_DOMAIN}
stage: ${env.STAGE}
name: ${env.REPO}
# url: ${env.URL}

serverless:
  component: '@sls-next/serverless-component@1.19.0-alpha.43'
  inputs:
    memory: 128
    bucketRegion: us-east-1
    bucketName: ${name}-${stage}
    name:
      defaultLambda: ${name}-${stage}-default
      apiLambda: ${name}-${stage}-api
      imageLambda: ${name}-${stage}-image
    domain: ['${sub}', codattest.com] # sub = 'dev' || 'www' (depending on stage)
    publicDirectoryCache: false
    useServerlessTraceTarget: true
    build:
      args: build:${stage} # replaces the default 'build' argument passed to next 
      env:
        MONGODB_URI: ${env.MONGODB_URI}
        NEXT_PUBLIC_STAGE: ${stage}
        NEXT_PUBLIC_STRIPE_PK: ${env.NEXT_PUBLIC_STRIPE_PK}
        STRIPE_SK: ${env.STRIPE_SK}
        NEXTAUTH_SECRET: ${env.NEXTAUTH_SECRET}
        NEXTAUTH_URL: ${env.NEXTAUTH_URL}